In [4]:
import pandas as pd
import numpy as np
from sklearn.impute import KNNImputer
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

In [2]:
main_df = pd.read_csv('arrhythmia.csv', header=None)
main_df.replace('?', np.nan, inplace=True)

In [3]:
knn_imputer=KNNImputer(n_neighbors=5)
main_df = pd.DataFrame(knn_imputer.fit_transform(main_df), columns=main_df.columns)
main_df[279]=main_df[279].astype('int')
main_df.iloc[0:5,0:11]

0    1      2     3      4      5      6      7      8     9     10
0  75.0  0.0  190.0  80.0   91.0  193.0  371.0  174.0  121.0 -16.0  13.0
1  56.0  1.0  165.0  64.0   81.0  174.0  401.0  149.0   39.0  25.0  37.0
2  54.0  0.0  172.0  95.0  138.0  163.0  386.0  185.0  102.0  96.0  34.0
3  55.0  0.0  175.0  94.0  100.0  202.0  380.0  179.0  143.0  28.0  11.0
4  75.0  0.0  190.0  80.0   88.0  181.0  360.0  177.0  103.0 -16.0  13.0

In [33]:
standard = StandardScaler()
main_df2 = pd.DataFrame(standard.fit_transform(main_df.iloc[:,:-1]), columns=range(279))
main_df2[279] = main_df[279]
main_df = main_df2
main_df

0         1         2         3         4         5         6    \
0    1.734439 -1.107520  0.641327  0.713814  0.135505  0.844945  0.113709   
1    0.579312  0.902918 -0.031998 -0.251644 -0.516072  0.420769  1.013301   
2    0.457720 -1.107520  0.156533  1.618932  3.197915  0.175193  0.563505   
3    0.518516 -1.107520  0.237332  1.558590  0.721924  1.045871  0.383587   
4    1.734439 -1.107520  0.641327  0.713814 -0.059968  0.577044 -0.216141   
5   -2.034923 -1.107520  0.075734 -1.036079  0.721924  0.264493 -1.385610   
6   -0.393427  0.902918 -0.166663 -0.975738 -0.776702 -0.583860  0.293628   
7    0.153739  0.902918 -0.112797 -0.855055 -0.711545 -3.463797  0.263641   
8   -0.150242 -1.107520  0.048801 -0.734373 -0.320599 -0.829436 -0.396059   
9    0.214535  0.902918  0.021868 -0.070621  0.005190 -0.561535  0.473546   
10   0.944089 -1.107520  0.102667  0.231085  0.852239 -0.449910  1.013301   
11  -0.089446  0.902918 -0.031998  1.075861 -0.776702 -0.271309  0.173682   
12   0.457720  0.902918  0.156533 -0.613691 -0.711545 -0.003408  0.443560   
13  -1.001388 -1.107520  0.102667  0.291426  0.135505  0.554719 -0.366073   
14  -0.150242  0.902918 -0.166663  1.196544 -0.776702  0.063567  0.953328   
15   0.032147  0.902918 -0.435993 -1.217102 -0.907018 -0.516885 -0.516005   
16   0.032147 -1.107520  0.129600 -0.553350 -0.450914 -0.226659 -0.605964   
17  -0.028650  0.902918 -0.220529 -0.613691 -1.232806 -0.784786 -0.426045   
18   1.612847 -1.107520 -0.031998 -0.311985  0.135505 -0.025733  0.743423   
19   0.640108  0.902918 -0.005065  0.231085 -0.450914  0.577044  0.953328   
20  -1.122980  0.902918 -0.166663 -0.613691 -0.385756  2.139801  0.473546   
21  -0.089446 -1.107520  0.075734 -0.070621  0.070347 -0.740136 -0.935814   
22  -0.636611  0.902918 -0.355194  0.412109 -1.167648 -0.516885 -0.096195   
23   0.640108  0.902918 -0.031998 -0.553350 -0.907018  0.041242  1.163233   
24  -0.393427  0.902918 -0.355194 -0.794714 -0.450914 -0.338284  0.623478   
25  -0.150242 -1.107520  0.075734  0.713814  1.308343 -0.606185  0.443560   
26  -0.758203 -1.107520  0.102667  0.291426  0.330978  0.688670  0.173682   
27  -0.940592  0.902918 -0.166663 -0.855055  0.396136  0.130543  1.193219   
28   0.579312  0.902918 -0.058931 -0.191303  0.070347  0.197518  1.583042   
29   0.275331  0.902918 -0.166663  0.894838  0.461293 -0.182009  0.983315   
..        ...       ...       ...       ...       ...       ...       ...   
422 -1.062184  0.902918 -0.112797 -0.674032 -0.385756  0.197518 -0.246127   
423  0.275331 -1.107520  0.533595  1.618932  0.330978  1.068196 -0.006236   
424 -2.399700 -1.107520 -1.270915 -2.846313  3.328231  0.041242  2.122797   
425 -0.636611 -1.107520  0.129600  1.498249 -0.125126 -0.115033 -0.156168   
426 -0.697407  0.902918 -0.166663 -0.915397 -2.210171  0.175193 -0.815868   
427  0.700904 -1.107520 -0.166663 -0.191303  2.872127 -0.159684  1.493083   
428  1.065681 -1.107520 -0.166663 -0.311985 -0.385756 -3.463797 -0.096195   
429 -2.338904  0.902918 -0.974652 -2.665290 -0.776702 -0.673161 -0.276114   
430 -2.156515 -1.107520 -0.759188 -2.363584  2.220550 -0.226659 -0.186154   
431  0.032147 -1.107520 -0.005065 -0.734373 -0.646387 -0.226659  0.413573   
432 -2.156515 -1.107520 -0.705322 -1.579149 -0.059968 -0.717811 -0.156168   
433  1.430458 -1.107520  0.021868 -0.493009 -0.581229 -0.137359 -2.315188   
434 -1.609350 -1.107520  0.318131 -0.191303 -0.059968 -0.003408 -0.216141   
435 -0.454223  0.902918 -0.058931 -0.372326 -0.646387 -0.003408 -0.006236   
436 -0.879796  0.902918 -0.058931 -0.674032 -0.776702 -0.248984 -0.815868   
437 -0.697407  0.902918 -0.301328 -0.311985 -0.125126 -0.293634  0.713437   
438 -0.575815 -1.107520  0.237332  0.834497 -0.059968 -0.204334 -0.306100   
439  0.153739  0.902918  0.048801 -0.130962  0.330978  0.331468  0.473546   
440 -0.575815 -1.107520  0.264265  0.231085 -0.059968 -0.048058  0.653464   
441 -0.575815  0.902918 -0.166663 -1.096420 -0.972175 -0.271309  0.203669   
442  1

In [13]:
X_train, X_test, Y_train, Y_test = train_test_split(main_df.iloc[:,0:-1], main_df[279],test_size=0.2)

In [16]:
knn_model_1 = KNeighborsClassifier(n_neighbors=1, metric='euclidean')
knn_model_30 = KNeighborsClassifier(n_neighbors=30, metric='euclidean')
knn_model_1.fit(X_train,Y_train)
knn_model_30.fit(X_train,Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
                     metric_params=None, n_jobs=None, n_neighbors=30, p=2,
                     weights='uniform')

In [18]:
from sklearn.metrics import classification_report, confusion_matrix

In [21]:
Y_knn_predicted_1 = knn_model_1.predict(X_test)
Y_knn_predicted_30 = knn_model_30.predict(X_test)

In [34]:
print(confusion_matrix(Y_knn_predicted_1, Y_test),'\n')
print(confusion_matrix(Y_knn_predicted_30, Y_test))
unique, counts = np.unique(Y_test, return_counts=True)
print('\n',dict(zip(unique, counts)))
pd.DataFrame(confusion_matrix(Y_knn_predicted_30, Y_test))

[[40  9  2  1  1  4  1  1  3  1  0  2]
 [ 1  2  0  0  0  0  0  0  0  0  0  1]
 [ 0  0  2  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  0  0  0  0  1  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 2  0  0  0  0  2  0  0  1  0  0  2]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  0  0  0  5  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  1  0  0  0  0  0  0  0  0  0  0]
 [ 2  0  0  0  1  1  0  0  0  0  0  0]] 

[[46 12  4  2  2  7  1  1 10  1  5]
 [ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]]

 {1: 46, 2: 12, 3: 4, 4: 2, 5: 2, 6: 7, 7: 1, 9: 1, 10: 10, 14: 1, 16: 5}


0   1   2   3   4   5   6   7   8   9   10
0   46  12   4   2   2   7   1   1  10   1   5
1    0   0   0   0   0   0   0   0   0   0   0
2    0   0   0   0   0   0   0   0   0   0   0
3    0   0   0   0   0   0   0   0   0   0   0
4    0   0   0   0   0   0   0   0   0   0   0
5    0   0   0   0   0   0   0   0   0   0   0
6    0   0   0   0   0   0   0   0   0   0   0
7    0   0   0   0   0   0   0   0   0   0   0
8    0   0   0   0   0   0   0   0   0   0   0
9    0   0   0   0   0   0   0   0   0   0   0
10   0   0   0   0   0   0   0   0   0   0   0

In [35]:
print(classification_report(Y_knn_predicted_1, Y_test),'\n')
print(classification_report(Y_knn_predicted_30, Y_test))

              precision    recall  f1-score   support

           1       0.87      0.62      0.72        65
           2       0.17      0.50      0.25         4
           3       0.50      1.00      0.67         2
           4       0.50      0.50      0.50         2
           5       0.00      0.00      0.00         0
           6       0.29      0.29      0.29         7
           7       0.00      0.00      0.00         0
           9       0.00      0.00      0.00         0
          10       0.50      0.83      0.62         6
          14       0.00      0.00      0.00         0
          15       0.00      0.00      0.00         1
          16       0.00      0.00      0.00         4

    accuracy                           0.57        91
   macro avg       0.24      0.31      0.25        91
weighted avg       0.71      0.57      0.61        91
 

              precision    recall  f1-score   support

           1       1.00      0.51      0.67        91
           2       0.0

c:\dev\python\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\dev\python\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [37]:
Y_train_pred_1=knn_model_1.predict(X_train)
Y_train_pred_30=knn_model_30.predict(X_train)

In [39]:
print(confusion_matrix(Y_train_pred_1, Y_train),'\n')
print(confusion_matrix(Y_train_pred_30, Y_train))
unique, counts = np.unique(Y_train, return_counts=True)
dict(zip(unique, counts))

[[199   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0  32   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0  11   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0  13   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0  11   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0  18   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   2   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   2   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   8   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0  40   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   3   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   5   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0  17]] 

[[199  32  11  13  11  18   2   2   8  39   3   5  17]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0  

{1: 199,
 2: 32,
 3: 11,
 4: 13,
 5: 11,
 6: 18,
 7: 2,
 8: 2,
 9: 8,
 10: 40,
 14: 3,
 15: 5,
 16: 17}

In [40]:
print(classification_report(Y_train_pred_1, Y_train),'\n')
print(classification_report(Y_train_pred_30, Y_train))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00       199
           2       1.00      1.00      1.00        32
           3       1.00      1.00      1.00        11
           4       1.00      1.00      1.00        13
           5       1.00      1.00      1.00        11
           6       1.00      1.00      1.00        18
           7       1.00      1.00      1.00         2
           8       1.00      1.00      1.00         2
           9       1.00      1.00      1.00         8
          10       1.00      1.00      1.00        40
          14       1.00      1.00      1.00         3
          15       1.00      1.00      1.00         5
          16       1.00      1.00      1.00        17

    accuracy                           1.00       361
   macro avg       1.00      1.00      1.00       361
weighted avg       1.00      1.00      1.00       361
 

              precision    recall  f1-score   support

           1       1.0

c:\dev\python\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [24]:
from sklearn.model_selection import GridSearchCV

In [26]:
param_grid={'n_neighbors':list(range(1,31)),'metric':['euclidean','manhattan']}

In [27]:
grid = GridSearchCV(knn_model_1,param_grid, verbose=3, cv=10, scoring='recall_weighted')
grid.fit(X_train,Y_train)

Fitting 10 folds for each of 60 candidates, totalling 600 fits
[CV] metric=euclidean, n_neighbors=1 .................................
[CV] ..... metric=euclidean, n_neighbors=1, score=0.541, total=   0.0s
[CV] metric=euclidean, n_neighbors=1 .................................
[CV] ..... metric=euclidean, n_neighbors=1, score=0.528, total=   0.0s
[CV] metric=euclidean, n_neighbors=1 .................................
[CV] ..... metric=euclidean, n_neighbors=1, score=0.528, total=   0.0s
[CV] metric=euclidean, n_neighbors=1 .................................
[CV] ..... metric=euclidean, n_neighbors=1, score=0.528, total=   0.0s
[CV] metric=euclidean, n_neighbors=1 .................................
[CV] ..... metric=euclidean, n_neighbors=1, score=0.556, total=   0.0s
[CV] metric=euclidean, n_neighbors=1 .................................
[CV] ..... metric=euclidean, n_neighbors=1, score=0.556, total=   0.0s
[CV] metric=euclidean, n_neighbors=1 .................................
[CV] ..... met

c:\dev\python\lib\site-packages\sklearn\model_selection\_split.py:667: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=10.
  % (min_groups, self.n_splits)), UserWarning)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s
c:\dev\python\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\dev\python\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg

[CV] ..... metric=euclidean, n_neighbors=1, score=0.694, total=   0.0s
[CV] metric=euclidean, n_neighbors=1 .................................
[CV] ..... metric=euclidean, n_neighbors=1, score=0.583, total=   0.0s
[CV] metric=euclidean, n_neighbors=1 .................................
[CV] ..... metric=euclidean, n_neighbors=1, score=0.500, total=   0.0s
[CV] metric=euclidean, n_neighbors=2 .................................
[CV] ..... metric=euclidean, n_neighbors=2, score=0.595, total=   0.0s
[CV] metric=euclidean, n_neighbors=2 .................................
[CV] ..... metric=euclidean, n_neighbors=2, score=0.583, total=   0.0s
[CV] metric=euclidean, n_neighbors=2 .................................
[CV] ..... metric=euclidean, n_neighbors=2, score=0.556, total=   0.0s
[CV] metric=euclidean, n_neighbors=2 .................................
[CV] ..... metric=euclidean, n_neighbors=2, score=0.556, total=   0.0s
[CV] metric=euclidean, n_neighbors=2 .................................
[CV] .

c:\dev\python\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


[CV] ..... metric=euclidean, n_neighbors=2, score=0.639, total=   0.0s
[CV] metric=euclidean, n_neighbors=2 .................................
[CV] ..... metric=euclidean, n_neighbors=2, score=0.611, total=   0.0s
[CV] metric=euclidean, n_neighbors=2 .................................
[CV] ..... metric=euclidean, n_neighbors=2, score=0.583, total=   0.0s
[CV] metric=euclidean, n_neighbors=2 .................................
[CV] ..... metric=euclidean, n_neighbors=2, score=0.556, total=   0.0s
[CV] metric=euclidean, n_neighbors=3 .................................
[CV] ..... metric=euclidean, n_neighbors=3, score=0.622, total=   0.0s
[CV] metric=euclidean, n_neighbors=3 .................................
[CV] ..... metric=euclidean, n_neighbors=3, score=0.556, total=   0.0s
[CV] metric=euclidean, n_neighbors=3 .................................
[CV] ..... metric=euclidean, n_neighbors=3, score=0.583, total=   0.0s
[CV] metric=euclidean, n_neighbors=3 .................................
[CV] .

[CV] ..... metric=euclidean, n_neighbors=9, score=0.528, total=   0.0s
[CV] metric=euclidean, n_neighbors=9 .................................
[CV] ..... metric=euclidean, n_neighbors=9, score=0.583, total=   0.0s
[CV] metric=euclidean, n_neighbors=9 .................................
[CV] ..... metric=euclidean, n_neighbors=9, score=0.556, total=   0.0s
[CV] metric=euclidean, n_neighbors=9 .................................
[CV] ..... metric=euclidean, n_neighbors=9, score=0.639, total=   0.0s
[CV] metric=euclidean, n_neighbors=9 .................................
[CV] ..... metric=euclidean, n_neighbors=9, score=0.583, total=   0.0s
[CV] metric=euclidean, n_neighbors=9 .................................
[CV] ..... metric=euclidean, n_neighbors=9, score=0.556, total=   0.0s
[CV] metric=euclidean, n_neighbors=9 .................................
[CV] ..... metric=euclidean, n_neighbors=9, score=0.583, total=   0.0s
[CV] metric=euclidean, n_neighbors=9 .................................
[CV] .

[CV] .... metric=euclidean, n_neighbors=15, score=0.556, total=   0.0s
[CV] metric=euclidean, n_neighbors=15 ................................
[CV] .... metric=euclidean, n_neighbors=15, score=0.583, total=   0.0s
[CV] metric=euclidean, n_neighbors=15 ................................
[CV] .... metric=euclidean, n_neighbors=15, score=0.556, total=   0.0s
[CV] metric=euclidean, n_neighbors=16 ................................
[CV] .... metric=euclidean, n_neighbors=16, score=0.568, total=   0.0s
[CV] metric=euclidean, n_neighbors=16 ................................
[CV] .... metric=euclidean, n_neighbors=16, score=0.556, total=   0.0s
[CV] metric=euclidean, n_neighbors=16 ................................
[CV] .... metric=euclidean, n_neighbors=16, score=0.556, total=   0.0s
[CV] metric=euclidean, n_neighbors=16 ................................
[CV] .... metric=euclidean, n_neighbors=16, score=0.556, total=   0.0s
[CV] metric=euclidean, n_neighbors=16 ................................
[CV] .

[CV] .... metric=euclidean, n_neighbors=22, score=0.556, total=   0.0s
[CV] metric=euclidean, n_neighbors=22 ................................
[CV] .... metric=euclidean, n_neighbors=22, score=0.556, total=   0.0s
[CV] metric=euclidean, n_neighbors=22 ................................
[CV] .... metric=euclidean, n_neighbors=22, score=0.556, total=   0.0s
[CV] metric=euclidean, n_neighbors=22 ................................
[CV] .... metric=euclidean, n_neighbors=22, score=0.583, total=   0.0s
[CV] metric=euclidean, n_neighbors=22 ................................
[CV] .... metric=euclidean, n_neighbors=22, score=0.583, total=   0.0s
[CV] metric=euclidean, n_neighbors=22 ................................
[CV] .... metric=euclidean, n_neighbors=22, score=0.556, total=   0.0s
[CV] metric=euclidean, n_neighbors=22 ................................
[CV] .... metric=euclidean, n_neighbors=22, score=0.556, total=   0.0s
[CV] metric=euclidean, n_neighbors=22 ................................
[CV] .

[CV] .... metric=euclidean, n_neighbors=28, score=0.583, total=   0.0s
[CV] metric=euclidean, n_neighbors=28 ................................
[CV] .... metric=euclidean, n_neighbors=28, score=0.556, total=   0.0s
[CV] metric=euclidean, n_neighbors=28 ................................
[CV] .... metric=euclidean, n_neighbors=28, score=0.556, total=   0.0s
[CV] metric=euclidean, n_neighbors=28 ................................
[CV] .... metric=euclidean, n_neighbors=28, score=0.556, total=   0.0s
[CV] metric=euclidean, n_neighbors=29 ................................
[CV] .... metric=euclidean, n_neighbors=29, score=0.514, total=   0.0s
[CV] metric=euclidean, n_neighbors=29 ................................
[CV] .... metric=euclidean, n_neighbors=29, score=0.556, total=   0.0s
[CV] metric=euclidean, n_neighbors=29 ................................
[CV] .... metric=euclidean, n_neighbors=29, score=0.556, total=   0.0s
[CV] metric=euclidean, n_neighbors=29 ................................
[CV] .

c:\dev\python\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\dev\python\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\dev\python\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\dev\python\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels w

[CV] ..... metric=manhattan, n_neighbors=1, score=0.444, total=   0.0s
[CV] metric=manhattan, n_neighbors=2 .................................
[CV] ..... metric=manhattan, n_neighbors=2, score=0.622, total=   0.0s
[CV] metric=manhattan, n_neighbors=2 .................................
[CV] ..... metric=manhattan, n_neighbors=2, score=0.528, total=   0.0s
[CV] metric=manhattan, n_neighbors=2 .................................
[CV] ..... metric=manhattan, n_neighbors=2, score=0.556, total=   0.0s
[CV] metric=manhattan, n_neighbors=2 .................................
[CV] ..... metric=manhattan, n_neighbors=2, score=0.583, total=   0.0s
[CV] metric=manhattan, n_neighbors=2 .................................
[CV] ..... metric=manhattan, n_neighbors=2, score=0.611, total=   0.0s
[CV] metric=manhattan, n_neighbors=2 .................................
[CV] ..... metric=manhattan, n_neighbors=2, score=0.639, total=   0.0s
[CV] metric=manhattan, n_neighbors=2 .................................
[CV] .

[CV] ..... metric=manhattan, n_neighbors=7, score=0.611, total=   0.0s
[CV] metric=manhattan, n_neighbors=7 .................................
[CV] ..... metric=manhattan, n_neighbors=7, score=0.583, total=   0.0s
[CV] metric=manhattan, n_neighbors=7 .................................
[CV] ..... metric=manhattan, n_neighbors=7, score=0.556, total=   0.0s
[CV] metric=manhattan, n_neighbors=8 .................................
[CV] ..... metric=manhattan, n_neighbors=8, score=0.595, total=   0.0s
[CV] metric=manhattan, n_neighbors=8 .................................
[CV] ..... metric=manhattan, n_neighbors=8, score=0.556, total=   0.0s
[CV] metric=manhattan, n_neighbors=8 .................................
[CV] ..... metric=manhattan, n_neighbors=8, score=0.583, total=   0.0s
[CV] metric=manhattan, n_neighbors=8 .................................
[CV] ..... metric=manhattan, n_neighbors=8, score=0.556, total=   0.0s
[CV] metric=manhattan, n_neighbors=8 .................................
[CV] .

[CV] .... metric=manhattan, n_neighbors=13, score=0.583, total=   0.0s
[CV] metric=manhattan, n_neighbors=13 ................................
[CV] .... metric=manhattan, n_neighbors=13, score=0.556, total=   0.0s
[CV] metric=manhattan, n_neighbors=13 ................................
[CV] .... metric=manhattan, n_neighbors=13, score=0.583, total=   0.0s
[CV] metric=manhattan, n_neighbors=13 ................................
[CV] .... metric=manhattan, n_neighbors=13, score=0.556, total=   0.0s
[CV] metric=manhattan, n_neighbors=14 ................................
[CV] .... metric=manhattan, n_neighbors=14, score=0.541, total=   0.0s
[CV] metric=manhattan, n_neighbors=14 ................................
[CV] .... metric=manhattan, n_neighbors=14, score=0.556, total=   0.0s
[CV] metric=manhattan, n_neighbors=14 ................................
[CV] .... metric=manhattan, n_neighbors=14, score=0.556, total=   0.0s
[CV] metric=manhattan, n_neighbors=14 ................................
[CV] .

[CV] .... metric=manhattan, n_neighbors=19, score=0.556, total=   0.0s
[CV] metric=manhattan, n_neighbors=19 ................................
[CV] .... metric=manhattan, n_neighbors=19, score=0.583, total=   0.0s
[CV] metric=manhattan, n_neighbors=19 ................................
[CV] .... metric=manhattan, n_neighbors=19, score=0.556, total=   0.0s
[CV] metric=manhattan, n_neighbors=19 ................................
[CV] .... metric=manhattan, n_neighbors=19, score=0.583, total=   0.0s
[CV] metric=manhattan, n_neighbors=19 ................................
[CV] .... metric=manhattan, n_neighbors=19, score=0.556, total=   0.0s
[CV] metric=manhattan, n_neighbors=20 ................................
[CV] .... metric=manhattan, n_neighbors=20, score=0.514, total=   0.0s
[CV] metric=manhattan, n_neighbors=20 ................................
[CV] .... metric=manhattan, n_neighbors=20, score=0.556, total=   0.0s
[CV] metric=manhattan, n_neighbors=20 ................................
[CV] .

[CV] .... metric=manhattan, n_neighbors=25, score=0.556, total=   0.0s
[CV] metric=manhattan, n_neighbors=25 ................................
[CV] .... metric=manhattan, n_neighbors=25, score=0.556, total=   0.0s
[CV] metric=manhattan, n_neighbors=25 ................................
[CV] .... metric=manhattan, n_neighbors=25, score=0.556, total=   0.0s
[CV] metric=manhattan, n_neighbors=25 ................................
[CV] .... metric=manhattan, n_neighbors=25, score=0.556, total=   0.0s
[CV] metric=manhattan, n_neighbors=25 ................................
[CV] .... metric=manhattan, n_neighbors=25, score=0.556, total=   0.0s
[CV] metric=manhattan, n_neighbors=26 ................................
[CV] .... metric=manhattan, n_neighbors=26, score=0.514, total=   0.0s
[CV] metric=manhattan, n_neighbors=26 ................................
[CV] .... metric=manhattan, n_neighbors=26, score=0.556, total=   0.0s
[CV] metric=manhattan, n_neighbors=26 ................................
[CV] .

[Parallel(n_jobs=1)]: Done 600 out of 600 | elapsed:   15.1s finished


GridSearchCV(cv=10, error_score=nan,
             estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                            metric='euclidean',
                                            metric_params=None, n_jobs=None,
                                            n_neighbors=1, p=2,
                                            weights='uniform'),
             iid='deprecated', n_jobs=None,
             param_grid={'metric': ['euclidean', 'manhattan'],
                         'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
                                         13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
                                         23, 24, 25, 26, 27, 28, 29, 30]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='recall_weighted', verbose=3)

In [30]:
grid.best_estimator_

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='manhattan',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [31]:
Y_knn_grid_prediction = grid.predict(X_test)
Y_knn_grid_prediction

array([ 1,  1,  1,  2,  1,  1,  1,  1,  2,  1,  1,  1,  1,  1,  1,  3,  1,
       15,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  5,  1,  1,  1,
        1,  1,  1,  1,  4,  1])

In [32]:
print(confusion_matrix(Y_knn_grid_prediction, Y_test),'\n')
print(classification_report(Y_knn_grid_prediction, Y_test))
pd.DataFrame(confusion_matrix(Y_knn_grid_prediction, Y_test))

[[46 10  3  1  1  7  1  1 10  1  0  4]
 [ 0  2  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]] 

              precision    recall  f1-score   support

           1       1.00      0.54      0.70        85
           2       0.17      1.00      0.29         2
           3       0.25      1.00      0.40         1
           4       0.50      1.00      0.67         1
           5       0.50      1.00      0.67         1
           6       0.00      0.00      0.00         0
           7       0.00      0.00      0.00         0
           9       0.00      0.00      0.00         0
          10       0.00      0.00      0.0

c:\dev\python\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\dev\python\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0   1   2   3   4   5   6   7   8   9   10  11
0   46  10   3   1   1   7   1   1  10   1   0   4
1    0   2   0   0   0   0   0   0   0   0   0   0
2    0   0   1   0   0   0   0   0   0   0   0   0
3    0   0   0   1   0   0   0   0   0   0   0   0
4    0   0   0   0   1   0   0   0   0   0   0   0
5    0   0   0   0   0   0   0   0   0   0   0   0
6    0   0   0   0   0   0   0   0   0   0   0   0
7    0   0   0   0   0   0   0   0   0   0   0   0
8    0   0   0   0   0   0   0   0   0   0   0   0
9    0   0   0   0   0   0   0   0   0   0   0   0
10   0   0   0   0   0   0   0   0   0   0   0   1
11   0   0   0   0   0   0   0   0   0   0   0   0